# Generated by Django 2.2.7 on 2020-03-03 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200303_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 9, 27, 6, 773420, tzinfo=utc)),
        ),
    ]
